### ISSUE TITLE
Words fail

### ISSUE THREAD

**Issue by tonymeira** [anonimbiri/gartic.io-hack#1]
Unfortunately the script does not detect words that have spaces, accents and special characters like "ç" and "-"
Can you fix it? thanks

**Comment by anonimbiri** [comment]
> Unfortunately the script does not detect words that have spaces, accents and special characters like "ç" and "-" Can you fix it? thanks

**Comment by anonimbiri** [comment]
> Unfortunately the script does not detect words that have spaces, accents and special characters like "ç" and "-" Can you fix it? thanks

I noticed that some characters can detect it too, but it should have been detecting spaces.

**Comment by anonimbiri** [comment]
I solved this problem in v0.8 version, I can close the issue
