### ISSUE TITLE
upload button

### ISSUE THREAD

**Issue by shubhamispro123** [anonimbiri/gartic.io-hack#11]
pls help after copying image link address i cant see upload button to show image

**Comment by anonimbiri** [comment]
stuck in old version
you should use drag and drop instead

**Comment by Mojang22** [comment]
> stuck in old version you should use drag and drop instead

doesn't work, it will stuck and nothing happend

**Comment by anonimbiri** [comment]
![](https://github.com/anonimbiri/gartic.io-hack/raw/main/screenshots/draw.gif)

**Comment by anonimbiri** [comment]
**If there is a boot problem, follow the steps below**
[solving the drawing problem](https://github.com/anonimbiri/gartic.io-hack/issues/9)
