### ISSUE TITLE
How can I change the opacity of the image copied from google?

### ISSUE THREAD

**Issue by WilliamApolinarioCode** [anonimbiri/gartic.io-hack#14]
I'm having problem to draw using the clipboard because the opacity is to high, I can't see what I'm drawing. Could you tell me how can I put a lower opacity? And also, how can I put new words to the Portuguese list?

**Comment by anonimbiri** [comment]
I'm lazy to do it, paste the url in the custom section

I was writing the codes from scratch, adding a menu or something.
I released it, I can't write the software
i'm too lazy

I understand that you are using an old version.
There was no opaque replacement.
and in newer versions i removed it
I added autodraw
