### ISSUE TITLE
Eski kelimeler

### ISSUE THREAD

**Issue by kedimen17** [anonimbiri/gartic.io-hack#2]
Gartic io ya yeni kelimeler eklendi ve bu script yeni kelimelerden haberdar değil, kelime ekleyip silebileceğimiz bir panel yapılabilir yada yeni kelimelerle scripti güncelleyebilirsn.

**Comment by anonimbiri** [comment]
v0.8 sürümünde Ğ, Ç v.b düzltildi kelime  eklemeye devem edeceğim.
