### ISSUE TITLE
How do i open the menu?

### ISSUE THREAD

**Issue by HelpPles** [anonimbiri/gartic.io-hack#4]
What buttons do i press to open the menu

**Comment by anonimbiri** [comment]
CTRL + M

**Comment by HelpPles** [comment]
I tried but it didnt work

**Comment by HelpPles** [comment]
when i check that the script is running on tampermonkey it doesn't say that it is running

**Comment by HelpPles** [comment]
Sure

**Comment by HelpPles** [comment]
![Screenshot 2022-01-18 101236](https://user-images.githubusercontent.com/94159612/149888427-ee13dbfa-61fd-4d47-8f62-446c1fd6ed8b.jpg)
 Here is the File

**Comment by HelpPles** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/94159612/149914131-3592140b-ad51-4590-823e-4ce6e34bc3fe.png">

**Comment by HelpPles** [comment]
That is proof i have the script installed

**Comment by anonimbiri** [comment]
> ![Screenshot 2022-01-18 101236](https://user-images.githubusercontent.com/94159612/149888427-ee13dbfa-61fd-4d47-8f62-446c1fd6ed8b.jpg) Here is the File

does not work there [https://gartic.io](gartic.io) works too

**Comment by HelpPles** [comment]
ok thank you
