### ISSUE TITLE
auto answer

### ISSUE THREAD

**Issue by HelpPles** [anonimbiri/gartic.io-hack#5]
The Auto answer isn't working could you tell me how to fix it

**Comment by anonimbiri** [comment]
![resim_2022-01-19_162231](https://user-images.githubusercontent.com/83531197/150139579-b760fb76-ea04-4d67-a9ab-7351e2c2af20.png)
is the list here empty?

if you don't see this list, it didn't give a hint

**Comment by anonimbiri** [comment]
![resim_2022-01-19_162708](https://user-images.githubusercontent.com/83531197/150140314-485f1a48-a0df-4718-aaac-b9c171175b3e.png)
when you see the list, when you press the pin button
you won't have to wait for the hint
